on: 
  schedule: 
    - cron: '0 0 * * 0'
  workflow_dispatch:


jobs:
  scrape:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          cache: 'pip'
      -
        name: Install build dependencies
        runs: pip install -r requirements.txt
      -
        name: Scraping SEP and Baseband firmwares
        runs: python main.py
      - 
        name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          branch: gh-pages
          folder: output
          git-config-name: GitHub Actions
          git-config-email: github-actions[bot]@users.noreply.github.com
